TARGET=CompB.pdf
LL=latexmk -pdf
CLEAN=latexmk -C

all: revision.tex $(TARGET) refresh

pdf: revision.tex $(TARGET) refresh

.PHONY : clean revision.tex $(TARGET) refresh showpdf 

revision.tex:
	echo "% Autogenerated, do not edit" > revision.tex
	echo "\\newcommand{\\revisiondate}{`git log -1 --format=\"%ad\" --date=short`}" >> revision.tex
	echo "\\newcommand{\\revision}{`git log -1 --format=\"%h\"`}" >> revision.tex

$(TARGET): $(TARGET:%.pdf=%.tex) $(SRC)
	$(LL) $<

clean:
	$(CLEAN)
	rm -f revision.tex

refresh:
	killall -HUP mupdf

mupdf:
	mupdf $(TARGET) &
