SHELL=bash
TARGET=CompB.pdf
LL=latexmk -pdf -pdflatex="pdflatex --shell-escape %O %S"
CLEAN=latexmk -C
export PATH := pygments:$(PATH) 


all: revision.tex $(TARGET) refresh

pdf: revision.tex $(TARGET) refresh

.PHONY : clean revision.tex $(TARGET) refresh mupdf

revision.tex:
	echo "% Autogenerated, do not edit" > revision.tex
	echo "\\newcommand{\\revisiondate}{`git log -1 --format=\"%ad\" --date=short`}" >> revision.tex
	echo "\\newcommand{\\revision}{`git log -1 --format=\"%h\"`}" >> revision.tex

$(TARGET): $(TARGET:%.pdf=%.tex) $(SRC)
	$(LL) $<

clean:
	$(CLEAN)
	rm -f revision.tex

refresh:
	-killall -HUP mupdf ||  echo "Mupdf not started, no refreshing."

mupdf:
	mupdf $(TARGET) &


# vim: set tabstop=4 shiftwidth=4 noexpandtab:
